### ISSUE TITLE
Error: EACCES: permission denied, open '/app/node_modules/vite-envs/client.d.ts'

### ISSUE THREAD

**Issue by lpoulter1** [garronej/vite-envs#30]
When I try to run the container I get a permissions error for this file but I can' see it in node modules?

here is my docker file
```
FROM node:20-alpine

WORKDIR /app
COPY --chown=node:node . ./
RUN npm ci
WORKDIR /app/client
RUN npm run build

EXPOSE ${FRONTEND_CLIENT_PORT}
USER node
CMD ["npm", "run", "preview"]

```

**Comment by garronej** [comment]
Hello @lpoulter1,

There are a few things here.  
First, let's see why this doesn't work.  
When you run `npm run preview`, the `vite-envs` Vite plugin is executed. It attempts to update your type definitions so that `import.meta.env` lists the environment variables you've declared.  
To do this, it needs to extend the base type definition of your version of Vite. Specifically, it needs to update `node_modules/vite-envs/client.d.ts`. However, you installed the dependencies as the default user, but you run `npm run preview` as the `node` user, leading to the EACCES error.  

To resolve this, you can move the `USER node` directive:  

```Dockerfile
FROM node:20-alpine

USER node
WORKDIR /app
COPY . ./
RUN npm ci
WORKDIR /app/client
RUN npm run build

EXPOSE ${FRONTEND_CLIENT_PORT}
CMD ["npm", "run", "preview"]
```

This will make the error disappear, but I strongly suggest you reconsider your approach.  

First, `vite preview` is not intended for use as a production web server—it's only for local testing.  
For performance, security, and reliability, you should consider using Nginx to serve your SPA instead.  
This will also make your Docker image **much** smaller, as you won't need to include the entire `node_modules` directory.  

```Dockerfile
# build environment
FROM node:20-alpine as build
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/client/nginx.conf /etc/nginx/conf.d/default.conf
RUN sed -i 's/8080/${FRONTEND_CLIENT_PORT}/g' /etc/nginx/conf.d/default.conf # Not fully sure about the syntax here

WORKDIR /usr/share/nginx/html
COPY --from=build /app/client/dist .
ENTRYPOINT sh -c "nginx -g 'daemon off;'"
```

`client/nginx.conf`  
```conf
server {
    listen 8080;

    gzip on; 
    gzip_vary on; 
    gzip_min_length 1024; 
    gzip_proxied expired no-cache no-store private auth; 
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/javascript application/xml; 
    gzip_disable "MSIE [1-6]\.";

    root /usr/share/nginx/html;
    index index.html;      

    try_files $uri $uri/ /index.html;

    # Vite generates filenames with hashes so we can
    # tell the browser to keep in cache the resources.
    location ^~ /static/ {
        try_files $uri =404;
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }

    location ~* \.(html|json|txt)$ {
        try_files $uri =404;
        expires -1;  # No cache for these file types
    }

}
```

This is the canonical setup for a containerized statically served single-page application (we're not talking about `vite-envs` here, it's the industry-standard approach).

Since you're using `vite-envs`, I assume you want to inject environment variables when running the Docker image, like so:  

`docker run --env FOO="xyz" my-org/my-vite-app`  

To make that work, you need to execute the shell script generated by `vite-envs` before you start serving your static files:  

```diff
-ENTRYPOINT sh -c "nginx -g 'daemon off;'"
+ENTRYPOINT sh -c "./vite-envs.sh && nginx -g 'daemon off;'"
```

With all that, you should be set!

**Comment by lpoulter1** [comment]
What a great answer thanks. I was aware of the limitations of preview and was writing that off as tebt debt until worked out the best way to serve the static bundle, so thanks for that config. I'll make thoose updates.
